### ISSUE TITLE
No module named 'numpy.distutils'

### ISSUE THREAD

**Issue by wzmumu** [mwageringel/guptri_py#1]
When I try to install `guptri_py`, an error occurs:  

from numpy.distutils.core import Extension
ModuleNotFoundError: No module named 'numpy.distutils'.

From the NumPy documentation I know that  "distutils has been deprecated in NumPy 1.23. 0 . It will be removed for Python 3.12".
Is there any method I can install guptri with a recent version of python and numpy?

**Comment by mwageringel** [comment]
I'm a bit out of the loop regarding the Python ecosystem changes unfortunately, but it looks like it's inevitable to migrate to a different build system like Meson to build the Fortran code: https://numpy.org/doc/stable/f2py/buildtools/meson.html

I'd be happy to accept a Pull Request.

The alternative would be downgrading to Python 3.11.

**Comment by wzmumu** [comment]
Thank you! I use Python 3.11 and it works.
